-- ============================================================
-- Migration 08 — statutory returns with digital approval, and a
-- tamper-evident audit trail
--
-- 1. STATUTORY RETURNS. A mine official prepares a periodic return; the
--    figures in it are generated by the database from the live records,
--    not typed in, and are fingerprinted (SHA-256) at submission. Corporate
--    management approves it or sends it back with a reason. Only approved
--    returns reach the regulator. Every step is attributable.
--
-- 2. HASH-CHAINED AUDIT LOG. Each audit entry stores the SHA-256 of its
--    own content plus the previous entry's hash. Altering, removing or
--    reordering any past entry breaks every hash after it, and
--    verify_audit_chain() reports exactly where. Combined with the
--    append-only triggers from migration 06, history can be added to but
--    not rewritten -- the practical guarantee a blockchain audit trail is
--    usually asked for, without running a blockchain.
--
-- Run after migration_07_field_operations.sql. Safe to re-run.
-- ============================================================

-- ------------------------------------------------------------
-- 1. Return snapshot: the figures, computed from the records
--
-- SECURITY INVOKER on purpose: it runs with the caller's RLS, so a mine
-- official can only ever generate a return for their own mine.
-- ------------------------------------------------------------
create or replace function generate_return_snapshot(p_mine uuid, p_start date, p_end date)
returns jsonb
language sql
stable
set search_path = public
as $$
select jsonb_build_object(
  'mine', (select jsonb_build_object('mine_id', m.mine_id, 'name', m.mine_name, 'state', m.state,
                                     'district', m.district, 'type', m.mine_type,
                                     'subsidiary', s.subsidiary_code)
             from mines m left join subsidiaries s on s.subsidiary_id = m.subsidiary_id
            where m.mine_id = p_mine),
  'period', jsonb_build_object('from', p_start, 'to', p_end),

  'compliance', (select jsonb_build_object(
      'due_in_period',     count(*),
      'completed',         count(*) filter (where c.status = 'Completed'),
      'completed_on_time', count(*) filter (where c.status = 'Completed' and c.completed_date <= c.due_date),
      'overdue',           count(*) filter (where c.status = 'Overdue'),
      'pending',           count(*) filter (where c.status = 'Pending'),
      'not_applicable',    count(*) filter (where c.status = 'Not Applicable'))
     from compliance_tracking c
    where c.mine_id = p_mine and c.due_date between p_start and p_end),

  'overdue_obligations', coalesce((select jsonb_agg(x order by x->>'due_date') from (
      select jsonb_build_object('requirement', i.requirement_summary, 'regulation', i.regulation_source,
                                'category', i.category, 'due_date', c.due_date) as x
        from compliance_tracking c join statutory_compliance_items i on i.item_id = c.item_id
       where c.mine_id = p_mine and c.status = 'Overdue' and c.due_date <= p_end
       order by c.due_date limit 50) q), '[]'::jsonb),

  'inspections', (select jsonb_build_object(
      'findings',          count(*),
      'critical',          count(*) filter (where g.severity = 'Critical'),
      'high',              count(*) filter (where g.severity = 'High'),
      'closed_verified',   count(*) filter (where g.corrective_action_status = 'Closed'),
      'awaiting_verification', count(*) filter (where g.corrective_action_status = 'Action Taken'),
      'open',              count(*) filter (where g.corrective_action_status in ('Open','In Progress','Reopened','Overdue')),
      'past_deadline',     count(*) filter (where g.corrective_action_status <> 'Closed' and g.action_due_date < p_end),
      'outside_geofence',  count(*) filter (where g.within_geofence = false))
     from geo_inspections g
    where g.mine_id = p_mine and g."timestamp"::date between p_start and p_end),

  'incidents', (select jsonb_build_object(
      'total',             count(*),
      'fatal',             count(*) filter (where i.incident_type = 'Fatal Accident'),
      'serious',           count(*) filter (where i.incident_type = 'Serious Injury'),
      'dangerous_occurrences', count(*) filter (where i.incident_type in ('Dangerous Occurrence','Fire','Inundation')),
      'near_misses',       count(*) filter (where i.incident_type = 'Near Miss'),
      'persons_killed',    coalesce(sum(i.persons_killed), 0),
      'persons_injured',   coalesce(sum(i.persons_injured), 0),
      'notifiable',        count(*) filter (where i.notifiable),
      'notified_on_time',  count(*) filter (where i.notifiable and i.dgms_notified
                                             and i.dgms_notified_at <= i.dgms_notice_due_at))
     from incidents i
    where i.mine_id = p_mine and i.occurred_at::date between p_start and p_end),

  'production', (select jsonb_build_object(
      'days_reported',     count(distinct p.production_date),
      'produced_t',        coalesce(sum(p.coal_produced_t), 0),
      'dispatched_t',      coalesce(sum(p.coal_dispatched_t), 0),
      'overburden_m3',     coalesce(sum(p.overburden_removed_m3), 0),
      'target_t',          coalesce(sum(p.target_t), 0))
     from mine_production_daily p
    where p.mine_id = p_mine and p.production_date between p_start and p_end),

  'environment', (select jsonb_build_object(
      'readings',          coalesce(sum(e.n), 0),
      'exceedances',       coalesce(sum(e.x), 0),
      'exceedances_by_parameter', coalesce(jsonb_object_agg(e.parameter, e.x) filter (where e.x > 0), '{}'::jsonb))
     from (select parameter, count(*) as n, count(*) filter (where exceeds_limit) as x
             from env_readings
            where mine_id = p_mine and reading_date between p_start and p_end
            group by parameter) e),

  'attendance', (select jsonb_build_object(
      'check_ins',         count(*),
      'persons',           count(distinct a.profile_id),
      'geofence_exceptions', count(*) filter (where a.check_in_within_geofence = false
                                                or a.check_out_within_geofence = false))
     from attendance_checkins a
    where a.mine_id = p_mine and (a.check_in_at at time zone 'Asia/Kolkata')::date between p_start and p_end),

  'grievances', (select jsonb_build_object(
      'filed',             count(*),
      'resolved',          count(*) filter (where g.status = 'Resolved'),
      'escalated',         count(*) filter (where g.escalated))
     from grievances g
    where g.mine_id = p_mine and g.date_filed between p_start and p_end)
)
$$;

create or replace function sha256_hex(p text)
returns text
language sql
immutable
as $$ select encode(sha256(convert_to(coalesce(p, ''), 'UTF8')), 'hex') $$;

-- ------------------------------------------------------------
-- 2. Returns and their approval workflow
-- ------------------------------------------------------------
create table if not exists statutory_returns (
    return_id       uuid primary key default uuid_generate_v4(),
    mine_id         uuid references mines(mine_id) not null,
    return_type     text not null,
    period_start    date not null,
    period_end      date not null,
    status          text not null default 'Draft',
    snapshot        jsonb,
    snapshot_hash   text,
    remarks         text,
    prepared_by     uuid references user_profiles(profile_id),
    prepared_at     timestamptz default now(),
    submitted_by    uuid references user_profiles(profile_id),
    submitted_at    timestamptz,
    reviewed_by     uuid references user_profiles(profile_id),
    reviewed_at     timestamptz,
    review_note     text,
    revision        int default 0,
    created_at      timestamptz default now(),
    unique (mine_id, return_type, period_start)
);

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'statutory_returns_status_check') then
    alter table statutory_returns add constraint statutory_returns_status_check
      check (status in ('Draft','Submitted','Returned','Approved'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'statutory_returns_type_check') then
    alter table statutory_returns add constraint statutory_returns_type_check
      check (return_type in ('Monthly Safety & Compliance Return',
                             'Monthly Production Return',
                             'Quarterly Environmental Return'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'statutory_returns_period_check') then
    alter table statutory_returns add constraint statutory_returns_period_check
      check (period_end >= period_start);
  end if;
end $$;

create or replace function statutory_returns_workflow()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  r  text := auth_role();
  me uuid := auth_profile_id();
begin
  -- Service role (seed scripts, jobs): not held to the workflow, but the
  -- figures and fingerprint still come from the database, never the caller.
  if auth.uid() is null then
    if new.snapshot is null or tg_op = 'INSERT' then
      new.snapshot := generate_return_snapshot(new.mine_id, new.period_start, new.period_end);
    end if;
    if new.status in ('Submitted','Approved') and new.snapshot_hash is null then
      new.snapshot_hash := sha256_hex(new.snapshot::text);
    end if;
    return new;
  end if;

  if tg_op = 'INSERT' then
    if r not in ('mine_official','corporate_admin','admin') then
      raise exception 'Returns are prepared by the mine official.';
    end if;
    new.status := 'Draft';
    new.prepared_by := me;
    new.prepared_at := now();
    new.submitted_by := null; new.submitted_at := null;
    new.reviewed_by := null;  new.reviewed_at := null; new.review_note := null;
    new.snapshot := generate_return_snapshot(new.mine_id, new.period_start, new.period_end);
    new.snapshot_hash := null;
    return new;
  end if;

  if old.status = 'Approved' then
    raise exception 'An approved return is final. File a revised return for the next period instead.';
  end if;
  if (new.mine_id, new.return_type, new.period_start, new.period_end)
     is distinct from (old.mine_id, old.return_type, old.period_start, old.period_end) then
    raise exception 'The mine, type and period of a return cannot be changed.';
  end if;

  if new.status in ('Draft','Submitted') then
    if old.status not in ('Draft','Returned') and not (old.status = 'Draft' and new.status = 'Draft') then
      raise exception 'Cannot move a % return to %.', old.status, new.status;
    end if;
    if r not in ('mine_official','corporate_admin','admin') then
      raise exception 'Only the mine official prepares and submits returns.';
    end if;
    -- Figures are always regenerated from the records; whatever the
    -- client sent in `snapshot` is ignored.
    new.snapshot := generate_return_snapshot(new.mine_id, new.period_start, new.period_end);
    new.reviewed_by := old.reviewed_by; new.reviewed_at := old.reviewed_at; new.review_note := old.review_note;
    if new.status = 'Submitted' then
      new.snapshot_hash := sha256_hex(new.snapshot::text);
      new.submitted_by  := me;
      new.submitted_at  := now();
      if old.status = 'Returned' then new.revision := coalesce(old.revision, 0) + 1; end if;
    else
      new.snapshot_hash := null;
      new.submitted_by := old.submitted_by; new.submitted_at := old.submitted_at;
    end if;
    return new;
  end if;

  -- Approve or send back
  if old.status <> 'Submitted' then
    raise exception 'Only a submitted return can be reviewed.';
  end if;
  if r not in ('corporate_admin','admin') then
    raise exception 'Returns are approved by corporate management.';
  end if;
  if me is not distinct from old.submitted_by then
    raise exception 'You submitted this return, so someone else must review it.';
  end if;
  if (new.snapshot, new.snapshot_hash, new.submitted_by, new.submitted_at, new.remarks)
     is distinct from (old.snapshot, old.snapshot_hash, old.submitted_by, old.submitted_at, old.remarks) then
    raise exception 'A reviewer cannot change the content of a return.';
  end if;
  if new.status = 'Returned' and coalesce(btrim(new.review_note), '') = '' then
    raise exception 'Say what needs to change before sending a return back.';
  end if;
  new.reviewed_by := me;
  new.reviewed_at := now();
  return new;
end $$;

drop trigger if exists trg_statutory_returns_workflow on statutory_returns;
create trigger trg_statutory_returns_workflow
  before insert or update on statutory_returns
  for each row execute function statutory_returns_workflow();

-- Approvals reach the right desk without anyone having to go looking.
create or replace function statutory_returns_notify()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare t text := mine_label(new.mine_id) || ': ' || new.return_type
                  || ' (' || to_char(new.period_start, 'Mon YYYY') || ')';
begin
  if new.status = 'Submitted' and (tg_op = 'INSERT' or old.status <> 'Submitted') then
    update alerts set status = 'Resolved'
     where source_table = 'statutory_returns' and split_part(source_id, ':', 1) = new.return_id::text
       and status in ('Open','Acknowledged');
    perform raise_alert('corporate_admin', new.mine_id, 'approval', 'Medium',
      t || ' awaiting approval', coalesce(new.remarks, 'Submitted for review.'),
      'statutory_returns', new.return_id::text || ':review', current_date + 7);
  elsif tg_op = 'UPDATE' and new.status in ('Approved','Returned') and old.status = 'Submitted' then
    update alerts set status = 'Resolved'
     where source_table = 'statutory_returns' and split_part(source_id, ':', 1) = new.return_id::text
       and status in ('Open','Acknowledged');
    if new.status = 'Returned' then
      perform raise_alert('mine_official', new.mine_id, 'approval', 'High',
        t || ' sent back', new.review_note,
        'statutory_returns', new.return_id::text || ':returned', current_date + 3);
    end if;
  end if;
  return null;
end $$;

drop trigger if exists trg_statutory_returns_notify on statutory_returns;
create trigger trg_statutory_returns_notify
  after insert or update on statutory_returns
  for each row execute function statutory_returns_notify();

drop trigger if exists trg_audit_statutory_returns on statutory_returns;
create trigger trg_audit_statutory_returns
  after insert or update on statutory_returns
  for each row execute function audit_row_change('return_id', 'snapshot');

alter table statutory_returns enable row level security;

-- The regulator sees returns only once corporate has approved them: a
-- draft is internal working, not a filing.
drop policy if exists "Read returns scoped" on statutory_returns;
create policy "Read returns scoped" on statutory_returns
  for select using (
    auth_role() in ('corporate_admin','admin')
    or (auth_role() = 'regulator' and status = 'Approved')
    or (auth_role() = 'mine_official' and mine_id = auth_mine_id())
  );

drop policy if exists "Prepare returns at own mine" on statutory_returns;
create policy "Prepare returns at own mine" on statutory_returns
  for insert with check (
    auth_role() in ('corporate_admin','admin')
    or (auth_role() = 'mine_official' and mine_id = auth_mine_id())
  );

drop policy if exists "Work on returns scoped" on statutory_returns;
create policy "Work on returns scoped" on statutory_returns
  for update using (
    auth_role() in ('corporate_admin','admin')
    or (auth_role() = 'mine_official' and mine_id = auth_mine_id())
  );

drop policy if exists "Discard own drafts" on statutory_returns;
create policy "Discard own drafts" on statutory_returns
  for delete using (
    status = 'Draft' and auth_role() = 'mine_official' and mine_id = auth_mine_id()
  );

create or replace view statutory_return_view as
select r.return_id, r.mine_id, m.mine_name, m.state, m.subsidiary_id,
       r.return_type, r.period_start, r.period_end, r.status, r.snapshot, r.snapshot_hash,
       r.remarks, r.review_note, r.revision,
       r.prepared_at, r.submitted_at, r.reviewed_at,
       r.submitted_by, r.reviewed_by,
       pb.full_name as prepared_by_name,
       sb.full_name as submitted_by_name,
       rb.full_name as reviewed_by_name
  from statutory_returns r
  left join mines m on m.mine_id = r.mine_id
  left join user_profiles pb on pb.profile_id = r.prepared_by
  left join user_profiles sb on sb.profile_id = r.submitted_by
  left join user_profiles rb on rb.profile_id = r.reviewed_by;
alter view statutory_return_view set (security_invoker = true);
grant select on statutory_return_view to authenticated;

-- ------------------------------------------------------------
-- 3. Hash chain on the audit log
-- ------------------------------------------------------------
alter table audit_log add column if not exists chain_seq bigint;
alter table audit_log add column if not exists prev_hash text;
alter table audit_log add column if not exists row_hash  text;

-- The exact bytes that get hashed. Any change to any of these fields --
-- or to the previous entry's hash -- changes the result.
create or replace function audit_entry_hash(p_seq bigint, p_prev text, p_actor uuid, p_action text,
                                            p_table text, p_record text, p_details jsonb,
                                            p_ts timestamptz)
returns text
language sql
immutable
as $$
  select sha256_hex(concat_ws('|',
    p_seq::text, p_prev, coalesce(p_actor::text, '-'), p_action,
    coalesce(p_table, '-'), coalesce(p_record, '-'), coalesce(p_details::text, '{}'),
    to_char(p_ts at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"')))
$$;

create or replace function audit_log_chain()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  last_seq  bigint;
  last_hash text;
begin
  -- Serialise appends so every entry links to exactly one predecessor.
  -- The lock is held until the inserting transaction commits.
  perform pg_advisory_xact_lock(hashtext('audit_log_chain'));
  select chain_seq, row_hash into last_seq, last_hash
    from audit_log where chain_seq is not null
   order by chain_seq desc limit 1;

  new."timestamp" := coalesce(new."timestamp", now());
  new.details     := coalesce(new.details, '{}'::jsonb);
  new.chain_seq   := coalesce(last_seq, 0) + 1;
  new.prev_hash   := coalesce(last_hash, 'GENESIS');
  new.row_hash    := audit_entry_hash(new.chain_seq, new.prev_hash, new.actor_uid, new.action,
                                      new.table_affected, new.record_id, new.details, new."timestamp");
  return new;
end $$;

-- Existing entries are chained once, in their original order. The
-- append-only guard is lifted for exactly this statement and restored.
do $$
declare
  rec record; seq bigint := 0; prev text := 'GENESIS';
begin
  if exists (select 1 from audit_log where chain_seq is null) then
    select coalesce(max(chain_seq), 0), coalesce(
             (select row_hash from audit_log where chain_seq is not null order by chain_seq desc limit 1),
             'GENESIS')
      into seq, prev from audit_log;
    alter table audit_log disable trigger trg_audit_log_no_update;
    for rec in select * from audit_log where chain_seq is null order by log_id loop
      seq := seq + 1;
      update audit_log
         set chain_seq = seq,
             prev_hash = prev,
             "timestamp" = coalesce(rec."timestamp", now()),
             details = coalesce(rec.details, '{}'::jsonb),
             row_hash  = audit_entry_hash(seq, prev, rec.actor_uid, rec.action, rec.table_affected,
                                          rec.record_id, coalesce(rec.details, '{}'::jsonb),
                                          coalesce(rec."timestamp", now()))
       where log_id = rec.log_id
       returning row_hash into prev;
    end loop;
    alter table audit_log enable trigger trg_audit_log_no_update;
  end if;
end $$;

drop trigger if exists trg_audit_log_chain on audit_log;
create trigger trg_audit_log_chain
  before insert on audit_log
  for each row execute function audit_log_chain();

create unique index if not exists uniq_audit_chain_seq on audit_log(chain_seq);

-- Walks the whole chain and recomputes every hash. Returns where it
-- first breaks, or ok=true. Callable by oversight roles and the service
-- role (the scheduler publishes the head hash externally after each run).
create or replace function verify_audit_chain()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  rec       record;
  expected  bigint := 1;
  prev      text   := 'GENESIS';
  checked   bigint := 0;
  computed  text;
begin
  if auth.uid() is not null and not is_oversight() then
    raise exception 'Only oversight roles can verify the audit chain.';
  end if;

  for rec in select * from audit_log order by chain_seq loop
    if rec.chain_seq is distinct from expected then
      return jsonb_build_object('ok', false, 'checked', checked, 'broken_at', expected,
        'reason', format('Entry %s is missing: the sequence jumps to %s. An entry has been removed.',
                         expected, rec.chain_seq));
    end if;
    if rec.prev_hash is distinct from prev then
      return jsonb_build_object('ok', false, 'checked', checked, 'broken_at', rec.chain_seq,
        'reason', format('Entry %s does not link to entry %s. The history has been reordered or replaced.',
                         rec.chain_seq, rec.chain_seq - 1));
    end if;
    computed := audit_entry_hash(rec.chain_seq, rec.prev_hash, rec.actor_uid, rec.action,
                                 rec.table_affected, rec.record_id, rec.details, rec."timestamp");
    if computed is distinct from rec.row_hash then
      return jsonb_build_object('ok', false, 'checked', checked, 'broken_at', rec.chain_seq,
        'reason', format('Entry %s has been altered: its contents no longer match its hash.', rec.chain_seq));
    end if;
    prev := rec.row_hash;
    expected := expected + 1;
    checked := checked + 1;
  end loop;

  return jsonb_build_object('ok', true, 'checked', checked,
                            'head_seq', expected - 1, 'head_hash', prev,
                            'verified_at', now());
end $$;
revoke execute on function verify_audit_chain() from public, anon;
grant execute on function verify_audit_chain() to authenticated, service_role;

-- The trail with actor names, for the oversight dashboards.
create or replace view audit_trail_view as
select a.log_id, a.chain_seq, a."timestamp", a.action, a.table_affected, a.record_id,
       a.details, a.prev_hash, a.row_hash, a.actor_uid,
       p.full_name as actor_name, p.role as actor_role
  from audit_log a
  left join user_profiles p on p.auth_uid = a.actor_uid;
alter view audit_trail_view set (security_invoker = true);
grant select on audit_trail_view to authenticated;

-- ============================================================
-- END OF MIGRATION 08
-- ============================================================
